import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // src/routeTree.gen.ts and src/lib/supabase/types.ts are both generated by external tools
    // (TanStack Router's dev/build step, `supabase gen types`) that know nothing about this
    // repo's prettier config -- linting them just reports thousands of formatting diffs against
    // a style they were never written to match, and CLAUDE.md already says never to hand-edit
    // either file. routeTree.gen.ts happens to currently pass anyway; excluding it too is just
    // future-proofing against its generator ever changing output style.
    ignores: ["dist", ".output", ".vinxi", "src/routeTree.gen.ts", "src/lib/supabase/types.ts"],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
